In [1]:
import numpy as np

In [2]:
def bam_encode(associations):
    left, right = associations[0]
    m = np.zeros((len(left), len(right)))
    for left, right in associations:
        left = np.matrix(left).T
        right = np.matrix(right)
        m += -2 * (left ^ right) + 1
    return m.astype(int)

def left_to_right(left, matrix):
    left = np.matrix(left)
    right = (left * matrix > 0).astype(int)
    return right.A1
    
def right_to_left(right, matrix):
    right = np.matrix(right).T
    left = (matrix * right > 0).astype(int)
    return left.A1

In [3]:
associations = [[[0, 1, 1, 1, 0, 1], [1, 1, 0, 0]],
                [[1, 0, 0, 1, 0, 0], [1, 0, 1, 0]]]

In [4]:
m = bam_encode(associations)
print(m)

[[ 0 -2  2  0]
 [ 0  2 -2  0]
 [ 0  2 -2  0]
 [ 2  0  0 -2]
 [-2  0  0  2]
 [ 0  2 -2  0]]


In [5]:
left_to_right([0, 1, 1, 1, 0, 1], m)

array([1, 1, 0, 0])

In [6]:
left_to_right([1, 0, 0, 1, 0, 0], m)

array([1, 0, 1, 0])

In [7]:
right_to_left([1, 1, 0, 0], m)

array([0, 1, 1, 1, 0, 1])

In [8]:
right_to_left([1, 0, 1, 0], m)

array([1, 0, 0, 1, 0, 0])