In [1]:
import numpy as np

In [2]:
def bam_encode(associations):
    left, right = associations[0]
    m = np.zeros((len(left), len(right)))
    for left, right in associations:
        left = np.matrix(left).T
        right = np.matrix(right)
        m += -2 * (left ^ right) + 1
    return m.astype(int)

def left_to_right(left, matrix):
    while True:
        left = np.matrix(left)
        right = (left * matrix > 0).astype(int)
        left_from_right = (matrix * right.T > 0).T.astype(int)
        if np.array_equal(left, left_from_right):
            return right.A1
        left = left_from_right
    
def right_to_left(right, matrix):
    while True:
        right = np.matrix(right)
        left = (matrix * right.T > 0).T.astype(int)
        right_from_left = (left * matrix > 0).astype(int)
        if np.array_equal(right, right_from_left):
            return left.A1
        right = right_from_left

In [3]:
lefts = np.loadtxt('data/BAM_X_simple.txt').astype(int)
print('data lefts:')
print(lefts)

rights = np.loadtxt('data/BAM_Y_simple.txt').astype(int)
print('data rights:')
print(rights)

n = len(lefts)
associations = [[lefts[i], rights[i]] for i in range(n)]
m = bam_encode(associations)
print('encoded weights:')
print(m)

print('decoded from data:')
for right in rights:
    left = right_to_left(right, m)
    print(right, '->', left)
for left in lefts:
    right = left_to_right(left, m)
    print(left, '->', right)

data lefts:
[[0 1 1 1 0 1]
 [1 0 0 1 0 0]]
data rights:
[[1 1 0 0]
 [1 0 1 0]]
encoded weights:
[[ 0 -2  2  0]
 [ 0  2 -2  0]
 [ 0  2 -2  0]
 [ 2  0  0 -2]
 [-2  0  0  2]
 [ 0  2 -2  0]]
decoded from data:
[1 1 0 0] -> [0 1 1 1 0 1]
[1 0 1 0] -> [1 0 0 1 0 0]
[0 1 1 1 0 1] -> [1 1 0 0]
[1 0 0 1 0 0] -> [1 0 1 0]


In [4]:
n = len(rights[0])
rights = [np.array(list(np.binary_repr(i, n)), dtype=int) for i in range(2**n)]
n = len(lefts[0])
lefts = [np.array(list(np.binary_repr(i, n)), dtype=int) for i in range(2**n)]

print('decoded from all possible inputs:')
for right in rights:
    left = right_to_left(right, m)
    print(right, '->', left)
for left in lefts:
    right = left_to_right(left, m)
    print(left, '->', right)

decoded from all possible inputs:
[0 0 0 0] -> [0 0 0 0 0 0]
[0 0 0 1] -> [0 0 0 0 1 0]
[0 0 1 0] -> [1 0 0 0 0 0]
[0 0 1 1] -> [1 0 0 0 1 0]
[0 1 0 0] -> [0 1 1 0 0 1]
[0 1 0 1] -> [0 1 1 0 1 1]
[0 1 1 0] -> [0 0 0 0 0 0]
[0 1 1 1] -> [0 0 0 0 1 0]
[1 0 0 0] -> [0 0 0 1 0 0]
[1 0 0 1] -> [0 0 0 0 0 0]
[1 0 1 0] -> [1 0 0 1 0 0]
[1 0 1 1] -> [1 0 0 0 0 0]
[1 1 0 0] -> [0 1 1 1 0 1]
[1 1 0 1] -> [0 1 1 0 0 1]
[1 1 1 0] -> [0 0 0 1 0 0]
[1 1 1 1] -> [0 0 0 0 0 0]
[0 0 0 0 0 0] -> [0 0 0 0]
[0 0 0 0 0 1] -> [0 1 0 0]
[0 0 0 0 1 0] -> [0 0 0 1]
[0 0 0 0 1 1] -> [0 1 0 1]
[0 0 0 1 0 0] -> [1 0 0 0]
[0 0 0 1 0 1] -> [1 1 0 0]
[0 0 0 1 1 0] -> [0 0 0 0]
[0 0 0 1 1 1] -> [0 1 0 0]
[0 0 1 0 0 0] -> [0 1 0 0]
[0 0 1 0 0 1] -> [0 1 0 0]
[0 0 1 0 1 0] -> [0 1 0 1]
[0 0 1 0 1 1] -> [0 1 0 1]
[0 0 1 1 0 0] -> [1 1 0 0]
[0 0 1 1 0 1] -> [1 1 0 0]
[0 0 1 1 1 0] -> [0 1 0 0]
[0 0 1 1 1 1] -> [0 1 0 0]
[0 1 0 0 0 0] -> [0 1 0 0]
[0 1 0 0 0 1] -> [0 1 0 0]
[0 1 0 0 1 0] -> [0 1 0 1]
[0 1 0 0 1 1] -> [0 1