In [1]:
import numpy as np

In [2]:
def bam_encode(associations):
    left, right = associations[0]
    m = np.zeros((len(left), len(right)))
    for left, right in associations:
        left = np.matrix(left).T
        right = np.matrix(right)
        m += -2 * (left ^ right) + 1
    return m.astype(int)

def left_to_right(left, matrix):
    left = np.matrix(left)
    right = (left * matrix > 0).astype(int)
    return right.A1
    
def right_to_left(right, matrix):
    right = np.matrix(right).T
    left = (matrix * right > 0).astype(int)
    return left.A1

In [3]:
lefts = np.loadtxt('data/BAM_X_simple.txt').astype(int)
rights = np.loadtxt('data/BAM_Y_simple.txt').astype(int)
n = len(lefts)
associations = [[lefts[i], rights[i]] for i in range(n)]

In [4]:
m = bam_encode(associations)

print(m)
print()

print('data:')
for right in rights:
    left = right_to_left(right, m)
    print(right, '->', left)
for left in lefts:
    right = left_to_right(left, m)
    print(left, '->', right)

n = len(rights[0])
rights = [np.array(list(np.binary_repr(i, n)), dtype=int) for i in range(2**n)]
n = len(lefts[0])
lefts = [np.array(list(np.binary_repr(i, n)), dtype=int) for i in range(2**n)]

print('all possible combinations:')
for right in rights:
    left = right_to_left(right, m)
    print(right, '->', left)
for left in lefts:
    right = left_to_right(left, m)
    print(left, '->', right)

[[ 0 -2  2  0]
 [ 0  2 -2  0]
 [ 0  2 -2  0]
 [ 2  0  0 -2]
 [-2  0  0  2]
 [ 0  2 -2  0]]

data:
[1 1 0 0] -> [0 1 1 1 0 1]
[1 0 1 0] -> [1 0 0 1 0 0]
[0 1 1 1 0 1] -> [1 1 0 0]
[1 0 0 1 0 0] -> [1 0 1 0]
all possible combinations:
[0 0 0 0] -> [0 0 0 0 0 0]
[0 0 0 1] -> [0 0 0 0 1 0]
[0 0 1 0] -> [1 0 0 0 0 0]
[0 0 1 1] -> [1 0 0 0 1 0]
[0 1 0 0] -> [0 1 1 0 0 1]
[0 1 0 1] -> [0 1 1 0 1 1]
[0 1 1 0] -> [0 0 0 0 0 0]
[0 1 1 1] -> [0 0 0 0 1 0]
[1 0 0 0] -> [0 0 0 1 0 0]
[1 0 0 1] -> [0 0 0 0 0 0]
[1 0 1 0] -> [1 0 0 1 0 0]
[1 0 1 1] -> [1 0 0 0 0 0]
[1 1 0 0] -> [0 1 1 1 0 1]
[1 1 0 1] -> [0 1 1 0 0 1]
[1 1 1 0] -> [0 0 0 1 0 0]
[1 1 1 1] -> [0 0 0 0 0 0]
[0 0 0 0 0 0] -> [0 0 0 0]
[0 0 0 0 0 1] -> [0 1 0 0]
[0 0 0 0 1 0] -> [0 0 0 1]
[0 0 0 0 1 1] -> [0 1 0 1]
[0 0 0 1 0 0] -> [1 0 0 0]
[0 0 0 1 0 1] -> [1 1 0 0]
[0 0 0 1 1 0] -> [0 0 0 0]
[0 0 0 1 1 1] -> [0 1 0 0]
[0 0 1 0 0 0] -> [0 1 0 0]
[0 0 1 0 0 1] -> [0 1 0 0]
[0 0 1 0 1 0] -> [0 1 0 1]
[0 0 1 0 1 1] -> [0 1 0 1]
[0 0 1 1 0 