In [1]:
import numpy as np

In [2]:
def bcm_encode(data):
    size = len(data[0])
    matrix = np.zeros((size, size), dtype=bool)
    for d in data:
        v = np.matrix(d)
        matrix = np.logical_or(matrix, v.T * v)
    return matrix

def bcm_decode(data, matrix, theta):
    return (data * matrix >= theta).A1.astype(int)

def is_known(decoded_data):
    return any(decoded_data)

In [3]:
data = [[1, 1, 0, 0, 0, 0],
        [0, 1, 0, 0, 0, 1]]

In [4]:
m = bcm_encode(data)
print(m.astype(int))

[[1 1 0 0 0 0]
 [1 1 0 0 0 1]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 1 0 0 0 1]]


In [5]:
a = bcm_decode([0, 1, 0, 0, 0, 1], m, 2)
print(a)
is_known(a)

[0 1 0 0 0 1]


True

In [6]:
a = bcm_decode([0, 1, 0, 1, 0, 0], m, 2)
print(a)
is_known(a)

[0 0 0 0 0 0]


False