In [1]:
import numpy as np

In [2]:
def bcm_encode(data):
    size = len(data[0])
    matrix = np.zeros((size, size), dtype=bool)
    for d in data:
        v = np.matrix(d)
        matrix = np.logical_or(matrix, v.T * v)
    return matrix

def bcm_decode(data, matrix, theta):
    return (data * matrix >= theta).A1.astype(int)

def is_known(decoded_data):
    return any(decoded_data)

In [3]:
data = np.loadtxt('data/BCM_simple.txt').astype(int)
m = bcm_encode(data)

print('BCM_simple:')
print(m.astype(int))
print()

print('actual data:')
for d in data:
    a = bcm_decode(d, m, 2)
    print(a, '->', 'known' if is_known(a) else 'unknown')

random_data = (np.random.rand(10, len(data[0])) > .5).astype(int)
print('random data:')
for d in random_data:
    a = bcm_decode(d, m, 2)
    print(a, '->', 'known' if is_known(a) else 'unknown')

BCM_simple:
[[1 1 0 0 0 0]
 [1 1 0 0 0 1]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 1 0 0 0 1]]

actual data:
[1 1 0 0 0 0] -> known
[0 1 0 0 0 1] -> known
random data:
[1 1 0 0 0 1] -> known
[0 0 0 0 0 0] -> unknown
[0 0 0 0 0 0] -> unknown
[0 0 0 0 0 0] -> unknown
[0 1 0 0 0 1] -> known
[0 1 0 0 0 1] -> known
[1 1 0 0 0 0] -> known
[0 1 0 0 0 0] -> known
[0 0 0 0 0 0] -> unknown
[1 1 0 0 0 1] -> known


In [4]:
data = np.loadtxt('data/BCM_simple6.txt').astype(int)
m = bcm_encode(data)

print('BCM_simple6:')
print(m.astype(int))
print()

print('actual data:')
for d in data:
    a = bcm_decode(d, m, 2)
    print(a, '->', 'known' if is_known(a) else 'unknown')

random_data = (np.random.rand(10, len(data[0])) > .5).astype(int)
print('random data:')
for d in random_data:
    a = bcm_decode(d, m, 2)
    print(a, '->', 'known' if is_known(a) else 'unknown')

BCM_simple6:
[[1 1 0 0 1 0]
 [1 1 0 0 0 1]
 [0 0 1 1 1 0]
 [0 0 1 1 0 1]
 [1 0 1 0 1 0]
 [0 1 0 1 0 1]]

actual data:
[1 1 0 0 0 0] -> known
[0 1 0 0 0 1] -> known
[0 0 1 1 0 0] -> known
[0 0 1 0 1 0] -> known
[0 0 0 1 0 1] -> known
[1 0 0 0 1 0] -> known
random data:
[0 0 1 0 1 0] -> known
[0 1 0 1 1 0] -> known
[0 0 0 0 0 0] -> unknown
[1 1 1 1 1 1] -> known
[1 0 0 0 1 0] -> known
[0 0 0 0 0 0] -> unknown
[0 0 1 1 1 0] -> known
[1 1 1 0 1 0] -> known
[1 1 1 1 1 1] -> known
[1 1 0 0 0 1] -> known
