In [1]:
import numpy as np

In [2]:
def bcm_encode(data):
    size = len(data[0])
    matrix = np.zeros((size, size), dtype=bool)
    for d in data:
        v = np.matrix(d)
        matrix = np.logical_or(matrix, v.T * v)
    return matrix

def bcm_decode(data, matrix, theta):
    return (data * matrix >= theta).A1.astype(int)

def is_known(decoded_data):
    return any(decoded_data)

In [3]:
theta = 2

In [4]:
data = np.loadtxt('data/BCM_simple.txt').astype(int)
print('simple data:')
print(data)

m = bcm_encode(data)
print('encoded weights:')
print(m.astype(int))
print()

print('decoded from data:')
for d in data:
    a = bcm_decode(d, m, theta)
    print(d, '->', 'known' if is_known(a) else 'unknown')
    
n = len(data[0])
data = [np.array(list(np.binary_repr(i, n)), dtype=int) for i in range(2**n)]
print('decoded from all possible inputs:')
for d in data:
    a = bcm_decode(d, m, theta)
    print(d, '->', 'known' if is_known(a) else 'unknown')

simple data:
[[1 1 0 0 0 0]
 [0 1 0 0 0 1]]
encoded weights:
[[1 1 0 0 0 0]
 [1 1 0 0 0 1]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 1 0 0 0 1]]

decoded from data:
[1 1 0 0 0 0] -> known
[0 1 0 0 0 1] -> known
decoded from all possible inputs:
[0 0 0 0 0 0] -> unknown
[0 0 0 0 0 1] -> unknown
[0 0 0 0 1 0] -> unknown
[0 0 0 0 1 1] -> unknown
[0 0 0 1 0 0] -> unknown
[0 0 0 1 0 1] -> unknown
[0 0 0 1 1 0] -> unknown
[0 0 0 1 1 1] -> unknown
[0 0 1 0 0 0] -> unknown
[0 0 1 0 0 1] -> unknown
[0 0 1 0 1 0] -> unknown
[0 0 1 0 1 1] -> unknown
[0 0 1 1 0 0] -> unknown
[0 0 1 1 0 1] -> unknown
[0 0 1 1 1 0] -> unknown
[0 0 1 1 1 1] -> unknown
[0 1 0 0 0 0] -> unknown
[0 1 0 0 0 1] -> known
[0 1 0 0 1 0] -> unknown
[0 1 0 0 1 1] -> known
[0 1 0 1 0 0] -> unknown
[0 1 0 1 0 1] -> known
[0 1 0 1 1 0] -> unknown
[0 1 0 1 1 1] -> known
[0 1 1 0 0 0] -> unknown
[0 1 1 0 0 1] -> known
[0 1 1 0 1 0] -> unknown
[0 1 1 0 1 1] -> known
[0 1 1 1 0 0] -> unknown
[0 1 1 1 0 1] -> known
[0 1 1 1 1 0

In [5]:
data = np.loadtxt('data/BCM_simple6.txt').astype(int)
print('simple6 data:')
print(data)

m = bcm_encode(data)
print('encoded weights:')
print(m.astype(int))
print()

print('decoded from data:')
for d in data:
    a = bcm_decode(d, m, theta)
    print(d, '->', 'known' if is_known(a) else 'unknown')
    
n = len(data[0])
data = [np.array(list(np.binary_repr(i, n)), dtype=int) for i in range(2**n)]
print('decoded from all possible inputs:')
for d in data:
    a = bcm_decode(d, m, theta)
    print(d, '->', 'known' if is_known(a) else 'unknown')

simple6 data:
[[1 1 0 0 0 0]
 [0 1 0 0 0 1]
 [0 0 1 1 0 0]
 [0 0 1 0 1 0]
 [0 0 0 1 0 1]
 [1 0 0 0 1 0]]
encoded weights:
[[1 1 0 0 1 0]
 [1 1 0 0 0 1]
 [0 0 1 1 1 0]
 [0 0 1 1 0 1]
 [1 0 1 0 1 0]
 [0 1 0 1 0 1]]

decoded from data:
[1 1 0 0 0 0] -> known
[0 1 0 0 0 1] -> known
[0 0 1 1 0 0] -> known
[0 0 1 0 1 0] -> known
[0 0 0 1 0 1] -> known
[1 0 0 0 1 0] -> known
decoded from all possible inputs:
[0 0 0 0 0 0] -> unknown
[0 0 0 0 0 1] -> unknown
[0 0 0 0 1 0] -> unknown
[0 0 0 0 1 1] -> unknown
[0 0 0 1 0 0] -> unknown
[0 0 0 1 0 1] -> known
[0 0 0 1 1 0] -> known
[0 0 0 1 1 1] -> known
[0 0 1 0 0 0] -> unknown
[0 0 1 0 0 1] -> known
[0 0 1 0 1 0] -> known
[0 0 1 0 1 1] -> known
[0 0 1 1 0 0] -> known
[0 0 1 1 0 1] -> known
[0 0 1 1 1 0] -> known
[0 0 1 1 1 1] -> known
[0 1 0 0 0 0] -> unknown
[0 1 0 0 0 1] -> known
[0 1 0 0 1 0] -> known
[0 1 0 0 1 1] -> known
[0 1 0 1 0 0] -> known
[0 1 0 1 0 1] -> known
[0 1 0 1 1 0] -> known
[0 1 0 1 1 1] -> known
[0 1 1 0 0 0] -> unknown
[0 1